### ISSUE TITLE
As developer I want to change ICheepRepository to async and remove Disposable interface 

### ISSUE THREAD

**Issue by Josh0104** [ITU-BDSA23-GROUP17/Chirp#181]
## Description  
Since all of our repository is async and does not implement the IDisposable interface, we should also do that in our `ICheepRepository` 
## Task 
- [x] Change `ICheepRepository` to async
- [x] Remove IDisposable interface 
- [x] Test if sending cheep is working as ir should

Note: You need to refactor in both `ICheepRepository`, `CheepRepository` and all files that implements the method from `CheepRepository`. Check in `src/Chirp.Web/pages `

**Comment by Josh0104** [comment]
All our repositories has now async in their methods, as well as `IDisposable` removed in all our repositories because we do not need. 
Also in our test classes have implemented the async methods from our src folder, were before it used non async methods
