### ISSUE TITLE
As a developer I want to use Github login authentication on the Chirp web application

### ISSUE THREAD

**Issue by Josh0104** [ITU-BDSA23-GROUP17/Chirp#88]
To the this task we can use the following solutions:

**1. ASP.NET Core Identity**
Write this command in terminal to start
`dotnet new webapp --auth Individual`

**2. Microsoft Identity Platform aka Entra ID Business to Consumer (B2C)**
- No built-in support for authorization.
- Will be replaced with Microsoft Entra ID for customers (public preview)

**3. Easy Auth**
- Built-in to Azure App Service (Web Apps + Functions) and Azure Container Apps
- Easy but somewhat limited.
- Superb for prototyping but also production ready
- No built-in support for authorization
- Only works on Azure

**Honorable mentions**
-ForgeRock
-Okta

### Task

- [ ] Create a login authentication using Github log in
- [ ] Create a webpage for when the users is login, so they can see their timeline 
- [ ] Save the user in a SQL database

**Comment by hananinas** [comment]
Working on adding users from GitHub and Microsoft to database on  `feat/github-cliams`
